spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userDB
    username: root
    password: Spacex@123


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: MYSQL
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
